server:
  servlet:
    encoding:
      charset: UTF-8    # 문자 인코딩을 UTF-8로 설정
      enabled: true     # 인코딩 설정을 활성화
      force: true       # 요청과 응답 모두 강제로 UTF-8 적용

spring:
  application:
    name: spring-board-mybatis
  profiles:
    active: local
  config:
    import: optional:file:.env[.properties]
  servlet:
    multipart:
      max-file-size: 10MB     # 단일 파일 최대 업로드 크기
      max-request-size: 20MB  # 전체 요청(여러 파일 합산) 최대 크기
  jwt:
    secret: ${JWT_SECRET_KEY}

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.spBoard.spring_board_mybatis
  configuration:
    map-underscore-to-camel-case: true
